export const books = [
    {
        number: 1,
        title: "O consolador prometido",
        subtitle: "Considerações acerca do surgimento do espiritismo",
        author: "João Ferreira",
        pdfUrl: "",
        coverUrl: "assets/cordeis/1.jpeg",
    },
    {
        number: 2,
        title: "Nossa dor, nossa mestra",
        subtitle: "A dor e o sofrimento sob a ótica espírita",
        author: "João Ferreira",
        pdfUrl: "",
        coverUrl: "assets/cordeis/2.jpeg",
    },
    {
        number: 3,
        title: "O tempo do homem e o tempo de Deus",
        subtitle: "A perspectiva temporal dos desejos humanos sob a ótica espírita",
        author: "João Ferreira",
        pdfUrl: "",
        coverUrl: "assets/cordeis/3.jpeg",
    },
    {
        number: 4,
        title: "Finados: Todos vivos, enfim!",
        subtitle: "A morte sob a ótica espírita",
        author: "João Ferreira",
        pdfUrl: "",
        coverUrl: "assets/cordeis/4.jpeg",
    },
    {
        number: 5,
        title: "Deixai vir a mim as criancinhas",
        subtitle: "",
        author: "João Ferreira",
        pdfUrl: "",
        coverUrl: "assets/cordeis/5.jpeg",
    },
    {
        number: 6,
        title: "Que eu veja, senhor!",
        subtitle: "A cura do cego de jericó",
        author: "João Ferreira",
        pdfUrl: "",
        coverUrl: "assets/cordeis/6.jpeg",
    },
    {
        number: 7,
        title: "A rainha das virtudes",
        subtitle: "A caridade sob a ótica espírita",
        author: "João Ferreira",
        pdfUrl: "",
        coverUrl: "assets/cordeis/7.jpeg",
    },
    {
        number: 8,
        title: "Pedi e recebereis",
        subtitle: "A prece sob a ótica espírita",
        author: "João Ferreira",
        pdfUrl: "",
        coverUrl: "assets/cordeis/8.jpeg",
    },
    {
        number: 9,
        title: "A família sob a ótica espírita",
        subtitle: "",
        author: "João Ferreira",
        pdfUrl: "",
        coverUrl: "assets/cordeis/9.jpeg",
    },
    {
        number: 10,
        title: "Perdoai para que Deus vos perdoe",
        subtitle: "O perdão sob a ótica espírita",
        author: "João Ferreira",
        pdfUrl: "",
        coverUrl: "assets/cordeis/10.jpeg",
    },
]