export const cordeis = [
    {
        number: 1,
        title: "O consolador prometido",
        subtitle: "Considerações acerca do surgimento do espiritismo",
        author: "João Ferreira",
        pdfUrl: "",
        frontCoverUrl: "assets/cordeis/01 - O consolador prometido/01.png",
        backCoverUrl: "assets/cordeis/01 - O consolador prometido/02.png"
    },
    {
        number: 2,
        title: "Nossa dor, nossa mestra",
        subtitle: "A dor e o sofrimento sob a ótica espírita",
        author: "João Ferreira",
        pdfUrl: "",
        frontCoverUrl: "assets/cordeis/02 - Nossa dor nossa mestra/01.png",
        backCoverUrl: "assets/cordeis/02 - Nossa dor nossa mestra/02.png"
    },
    {
        number: 5,
        title: "Deixai vir a mim as criancinhas",
        author: "João Ferreira",
        pdfUrl: "",
        frontCoverUrl: "assets/cordeis/05 - Deixai vir a mim as criancinhas/01.png",
        backCoverUrl: "assets/cordeis/05 - Deixai vir a mim as criancinhas/02.png"
    },
    {
        number: 9,
        title: "A família sob a ótica espírita",
        author: "João Ferreira",
        pdfUrl: "",
        frontCoverUrl: "assets/cordeis/09 - A família sob a ótica espírita/01.png",
        backCoverUrl: "assets/cordeis/09 - A família sob a ótica espírita/02.png",
    },
    {
        number: 11,
        title: "O homem de bem sob a ótica espírita",
        author: "João Ferreira",
        pdfUrl: "",
        frontCoverUrl: "assets/cordeis/11 - O homem de bem sob a ótica espírita/01.png",
        backCoverUrl: "assets/cordeis/11 - O homem de bem sob a ótica espírita/02.png",
    },
    {
        number: 19,
        title: "A felicidade sob a ótica espírita",
        author: "João Ferreira",
        pdfUrl: "",
        frontCoverUrl: "assets/cordeis/19 - A felicidade sob a ótica espírita/01.png",
        backCoverUrl: "assets/cordeis/19 - A felicidade sob a ótica espírita/02.png",
    },
    {
        number: 20,
        title: "20 - A cremação de corpos",
        author: "João Ferreira",
        subtitle: "O destino dos cadáveres sob a ótica espírita",
        pdfUrl: "",
        frontCoverUrl: "assets/cordeis/20 - A cremação de corpos/01.png",
        backCoverUrl: "assets/cordeis/20 - A cremação de corpos/02.png",
    },
    {
        number: 21,
        title: "Mediunidade ultrajada",
        author: "João Ferreira",
        subtitle: "Os falsos profetas sob a ótica espírita",
        pdfUrl: "",
        frontCoverUrl: "assets/cordeis/21 - Mediunidade ultrajada/01.png",
        backCoverUrl: "assets/cordeis/21 - Mediunidade ultrajada/02.png",
    },
    {
        number: 22,
        title: "Os sonhos sob a ótica espírita",
        author: "João Ferreira",
        pdfUrl: "",
        frontCoverUrl: "assets/cordeis/22 - Os sonhos sob a ótica espírita/01.png",
        backCoverUrl: "assets/cordeis/22 - Os sonhos sob a ótica espírita/02.png",
    },
    {
        number: 23,
        title: "Causa e efeito",
        subtitle: "Considerações acerca da lei do retorno",
        author: "João Ferreira",
        pdfUrl: "",
        frontCoverUrl: "assets/cordeis/23 - Causa e efeito/01.png",
        backCoverUrl: "assets/cordeis/23 - Causa e efeito/02.png",
    },
    {
        number: 24,
        title: "Judas à luz da misericórdia",
        subtitle: "Considerações em torno da figura de judas iscariotes",
        author: "João Ferreira",
        pdfUrl: "",
        frontCoverUrl: "assets/cordeis/24 - Judas à luz da misericórdia/01.png",
        backCoverUrl: "assets/cordeis/24 - Judas à luz da misericórdia/02.png",
    },
    {
        number: 25,
        title: "Mestre, por que choras",
        subtitle: "Lições retiradas do choro de Jesus",
        author: "João Ferreira",
        pdfUrl: "",
        frontCoverUrl: "assets/cordeis/25 - Mestre, por que choras/01.png",
        backCoverUrl: "assets/cordeis/25 - Mestre, por que choras/02.png",
    },
    {
        number: 26,
        title: "A porta estreita",
        author: "João Ferreira",
        pdfUrl: "",
        frontCoverUrl: "assets/cordeis/26 - A porta estreita/01.png",
        backCoverUrl: "assets/cordeis/26 - A porta estreita/02.png",
    },
    {
        number: 27,
        title: "27 - Por que morrem as flores",
        subtitle: "As mortes prematuras sob a ótica espírita",
        author: "João Ferreira",
        pdfUrl: "",
        frontCoverUrl: "assets/cordeis/27 - Por que morrem as flores/01.png",
        backCoverUrl: "assets/cordeis/27 - Por que morrem as flores/02.png",
    },
    {
        number: 28,
        title: "Culpa e remorso",
        author: "João Ferreira",
        pdfUrl: "",
        frontCoverUrl: "assets/cordeis/28 - Culpa e remorso/01.png",
        backCoverUrl: "assets/cordeis/28 - Culpa e remorso/02.png",
    },
    {
        number: 29,
        title: "Eu sou",
        subtitle: "A busca pelo Cristo consolador",
        author: "João Ferreira",
        pdfUrl: "",
        frontCoverUrl: "assets/cordeis/29 - Eu sou/01.png",
        backCoverUrl: "assets/cordeis/29 - Eu sou/02.png",
    },
    {
        number: 30,
        title: "Um olhar para os pobres e estropiados",
        author: "João Ferreira",
        pdfUrl: "",
        frontCoverUrl: "assets/cordeis/30 - Um olhar para os pobres e estropiados/01.png",
        backCoverUrl: "assets/cordeis/30 - Um olhar para os pobres e estropiados/02.png",
    },
    {
        number: 34,
        title: "Gratidão sob a ótica espírita",
        author: "João Ferreira",
        pdfUrl: "",
        frontCoverUrl: "assets/cordeis/34 - Gratidão sob a ótica espírita/01.png",
        backCoverUrl: "assets/cordeis/34 - Gratidão sob a ótica espírita/02.png",
    },
    {
        number: 35,
        title: "Animais, nós também.",
        subtitle: "A evolução dos animais sob a ótica espírita",
        author: "João Ferreira",
        pdfUrl: "",
        frontCoverUrl: "assets/cordeis/35 - Animais, nós também/01.png",
        backCoverUrl: "assets/cordeis/35 - Animais, nós também/02.png",
    },
    {
        number: 37,
        title: "A depressão sob a ótica espírita",
        author: "João Ferreira",
        pdfUrl: "",
        frontCoverUrl: "assets/cordeis/37 -  A depressão sob a ótica espírita/01.png",
        backCoverUrl: "assets/cordeis/37 -  A depressão sob a ótica espírita/02.png",
    },
    {
        number: 38,
        title: "Superiores e subordinados",
        subtitle: "A autoridade sob a ótica espírita",
        author: "João Ferreira",
        pdfUrl: "",
        frontCoverUrl: "assets/cordeis/38 - Superiores e subordinados/01.png",
        backCoverUrl: "assets/cordeis/38 - Superiores e subordinados/02.png",
    },
    {
        number: 39,
        title: "Vampirismo espiritual e emocional",
        author: "João Ferreira",
        pdfUrl: "",
        frontCoverUrl: "assets/cordeis/39 - Vampirismo espiritual e emocional/01.png",
        backCoverUrl: "assets/cordeis/39 - Vampirismo espiritual e emocional/02.png",
    },
    {
        number: 40,
        title: "Deus",
        subtitle: "A evolução do pensamento humano sobre a existência do criador",
        author: "João Ferreira",
        pdfUrl: "",
        frontCoverUrl: "assets/cordeis/40 - Deus/01.png",
        backCoverUrl: "assets/cordeis/40 - Deus/02.png",
    },
    {
        number: 41,
        title: "O recurso terapêutico do passe 1",
        author: "João Ferreira",
        pdfUrl: "",
        frontCoverUrl: "assets/cordeis/41 - O recurso terapêutico do passe 1/01.png",
        backCoverUrl: "assets/cordeis/41 - O recurso terapêutico do passe 1/02.png",
    },
    {
        number: 42,
        title: "O recurso terapêutico do passe 2",
        subtitle: "O autopasse",
        author: "João Ferreira",
        pdfUrl: "",
        frontCoverUrl: "assets/cordeis/42 - O recurso terapêutico do passe 2/01.png",
        backCoverUrl: "assets/cordeis/42 - O recurso terapêutico do passe 2/02.png",
    },
    {
        number: 43,
        title: "O recurso terapêutico do passe 3",
        subtitle: "Magnetismo na água",
        author: "João Ferreira",
        pdfUrl: "",
        frontCoverUrl: "assets/cordeis/43 - O recurso terapêutico do passe 3/01.png",
        backCoverUrl: "assets/cordeis/43 - O recurso terapêutico do passe 3/02.png",
    },
    {
        number: 44,
        title: "Lições da parábola",
        author: "João Ferreira",
        pdfUrl: "",
        frontCoverUrl: "assets/cordeis/44 - Lições da parábola/01.png",
        backCoverUrl: "assets/cordeis/44 - Lições da parábola/02.png",
    },
    {
        number: 45,
        title: "45 - Embainha tua espada",
        subtitle: "A conduta cristã diante das agressões",
        author: "João Ferreira",
        pdfUrl: "",
        frontCoverUrl: "assets/cordeis/45 - Embainha tua espada/01.png",
        backCoverUrl: "assets/cordeis/45 - Embainha tua espada/02.png",
    },
    {
        number: 46,
        title: "A compaixão sob a ótica espírita",
        author: "João Ferreira",
        pdfUrl: "",
        frontCoverUrl: "assets/cordeis/46 - A compaixão sob a ótica espírita/01.png",
        backCoverUrl: "assets/cordeis/46 - A compaixão sob a ótica espírita/02.png",
    },
    {
        number: 47,
        title: "Espíritos protetores, familiares e simpáticos",
        subtitle: "A missão dos anjos guardiões",
        author: "João Ferreira",
        pdfUrl: "",
        frontCoverUrl: "assets/cordeis/47 - Espíritos protetores, familiares e simpáticos/01.png",
        backCoverUrl: "assets/cordeis/47 - Espíritos protetores, familiares e simpáticos/02.png",
    },
    {
        number: 48,
        title: "Tatuagem sob a otica espirita",
        author: "João Ferreira",
        pdfUrl: "",
        frontCoverUrl: "assets/cordeis/48 - Tatuagem sob a otica espirita/01.png",
        backCoverUrl: "assets/cordeis/48 - Tatuagem sob a otica espirita/02.png",
    },
    {
        number: 49,
        title: "Transição planetária",
        subtitle: "A transformação da terra em mundo de regeneração",
        author: "João Ferreira",
        pdfUrl: "",
        frontCoverUrl: "assets/cordeis/49 - Transição planetária/01.png",
        backCoverUrl: "assets/cordeis/49 - Transição planetária/02.png",
    },
    {
        number: 50,
        title: "Paraíso, inferno e purgatório",
        author: "João Ferreira",
        pdfUrl: "",
        frontCoverUrl: "assets/cordeis/50 - Paraíso, inferno e purgatório/01.png",
        backCoverUrl: "assets/cordeis/50 - Paraíso, inferno e purgatório/02.png",
    },
    {
        number: 51,
        title: "Pilares da doutrina espírita",
        author: "João Ferreira",
        pdfUrl: "",
        frontCoverUrl: "assets/cordeis/51 - Pilares da doutrina espírita/01.png",
        backCoverUrl: "assets/cordeis/51 - Pilares da doutrina espírita/02.png",
    },
]