export const cordeis = [
    {
        number: 1,
        type: "cordel",
        category: "Amor e Fé",
        title: "O consolador prometido",
        subtitle: "Considerações acerca do surgimento do espiritismo",
        author: "João Ferreira",
        pdfUrl: "https://drive.google.com/file/d/10QHW43ZPmQN-Qw_-iEy1DaqC-QeW71eH/view?usp=sharing",
        frontCoverUrl: "assets/cordeis/01 - O consolador prometido/01.png",
        backCoverUrl: "assets/cordeis/01 - O consolador prometido/02.png"
    },
    {
        number: 2,
        type: "cordel",
        category: "Amor e Fé",
        title: "Nossa dor, nossa mestra",
        subtitle: "A dor e o sofrimento sob a ótica espírita",
        author: "João Ferreira",
        pdfUrl: "https://drive.google.com/file/d/1DmwjnJF-wYrC_XWQO6VX1R3ieDARWGfs/view?usp=sharing",
        frontCoverUrl: "assets/cordeis/02 - Nossa dor nossa mestra/01.png",
        backCoverUrl: "assets/cordeis/02 - Nossa dor nossa mestra/02.png"
    },
    {
        number: 5,
        category: "Amor e Fé",
        type: "cordel",
        title: "Deixai vir a mim as criancinhas",
        author: "João Ferreira",
        pdfUrl: "https://drive.google.com/file/d/1o_CJuA53hKYptdZND_Ei9fk0XXFfFCkg/view?usp=sharing",
        frontCoverUrl: "assets/cordeis/05 - Deixai vir a mim as criancinhas/01.png",
        backCoverUrl: "assets/cordeis/05 - Deixai vir a mim as criancinhas/02.png"
    },
    {
        number: 9,
        category: "Amor e Fé",
        type: "cordel",
        title: "A família sob a ótica espírita",
        author: "João Ferreira",
        pdfUrl: "https://drive.google.com/file/d/17UqddbqXa3Z37zHMAaKsfO_xyPYusMxL/view?usp=sharing",
        frontCoverUrl: "assets/cordeis/09 - A família sob a ótica espírita/01.png",
        backCoverUrl: "assets/cordeis/09 - A família sob a ótica espírita/02.png",
    },
    {
        number: 11,
        category: "Amor e Fé",
        type: "cordel",
        title: "O homem de bem sob a ótica espírita",
        author: "João Ferreira",
        pdfUrl: "https://drive.google.com/file/d/1u5TDXbqPym3mp9sC9-kMlt0dmlFqbSBT/view?usp=sharing",
        frontCoverUrl: "assets/cordeis/11 - O homem de bem sob a ótica espírita/01.png",
        backCoverUrl: "assets/cordeis/11 - O homem de bem sob a ótica espírita/02.png",
    },
    {
        number: 19,
        category: "Amor e Fé",
        type: "cordel",
        title: "A felicidade sob a ótica espírita",
        author: "João Ferreira",
        pdfUrl: "https://drive.google.com/file/d/1eBTzBkFMm5G4pi4zJYWTFm7ar5Acwndi/view?usp=sharing",
        frontCoverUrl: "assets/cordeis/19 - A felicidade sob a ótica espírita/01.png",
        backCoverUrl: "assets/cordeis/19 - A felicidade sob a ótica espírita/02.png",
    },
    {
        number: 20,
        type: "cordel",
        category: "Vida após a Morte",
        title: "A cremação de corpos",
        author: "João Ferreira",
        subtitle: "O destino dos cadáveres sob a ótica espírita",
        pdfUrl: "https://drive.google.com/file/d/1z02LVWXeewBQTMsfl4HT8NjJT0T39Xbv/view?usp=sharing",
        frontCoverUrl: "assets/cordeis/20 - A cremação de corpos/01.png",
        backCoverUrl: "assets/cordeis/20 - A cremação de corpos/02.png",
    },
    {
        number: 21,
        type: "cordel",
        category: "Vida após a Morte",
        title: "Mediunidade ultrajada",
        author: "João Ferreira",
        subtitle: "Os falsos profetas sob a ótica espírita",
        pdfUrl: "https://drive.google.com/file/d/1UtI7w2V6SWuFSO5KF6OvRIQDgPUzWzJ4/view?usp=sharing",
        frontCoverUrl: "assets/cordeis/21 - Mediunidade ultrajada/01.png",
        backCoverUrl: "assets/cordeis/21 - Mediunidade ultrajada/02.png",
    },
    {
        number: 22,
        type: "cordel",
        category: "Vida após a Morte",
        title: "Os sonhos sob a ótica espírita",
        author: "João Ferreira",
        pdfUrl: "https://drive.google.com/file/d/1tWXLa60yNj_22SFXANe3UHDI2zngCgA8/view?usp=sharing",
        frontCoverUrl: "assets/cordeis/22 - Os sonhos sob a ótica espírita/01.png",
        backCoverUrl: "assets/cordeis/22 - Os sonhos sob a ótica espírita/02.png",
    },
    {
        number: 23,
        type: "cordel",
        category: "Vida após a Morte",
        title: "Causa e efeito",
        subtitle: "Considerações acerca da lei do retorno",
        author: "João Ferreira",
        pdfUrl: "https://drive.google.com/file/d/1bYFrycgE0ZmDQ3Epaw5owqWpnBUpzgo6/view?usp=sharing",
        frontCoverUrl: "assets/cordeis/23 - Causa e efeito/01.png",
        backCoverUrl: "assets/cordeis/23 - Causa e efeito/02.png",
    },
    {
        number: 24,
        type: "cordel",
        category: "Vida após a Morte",
        title: "Judas à luz da misericórdia",
        subtitle: "Considerações em torno da figura de judas iscariotes",
        author: "João Ferreira",
        pdfUrl: "https://drive.google.com/file/d/1uDhdnpv9xasmoKBIlqQWZK427Cz-L6OE/view?usp=sharing",
        frontCoverUrl: "assets/cordeis/24 - Judas à luz da misericórdia/01.png",
        backCoverUrl: "assets/cordeis/24 - Judas à luz da misericórdia/02.png",
    },
    {
        number: 25,
        type: "cordel",
        category: "Vida após a Morte",
        title: "Mestre, por que choras",
        subtitle: "Lições retiradas do choro de Jesus",
        author: "João Ferreira",
        pdfUrl: "https://drive.google.com/file/d/1FjTfq9K07OucxCOSbnjMfiZ3EvJyWNQe/view?usp=sharing",
        frontCoverUrl: "assets/cordeis/25 - Mestre, por que choras/01.png",
        backCoverUrl: "assets/cordeis/25 - Mestre, por que choras/02.png",
    },
    {
        number: 26,
        type: "cordel",
        category: "Vida após a Morte",
        title: "A porta estreita",
        author: "João Ferreira",
        pdfUrl: "https://drive.google.com/file/d/1GEC8X4tFYvctWmB82rMHMZg7f9GU1ziZ/view?usp=sharing",
        frontCoverUrl: "assets/cordeis/26 - A porta estreita/01.png",
        backCoverUrl: "assets/cordeis/26 - A porta estreita/02.png",
    },
    {
        number: 27,
        type: "cordel",
        category: "Vida após a Morte",
        title: "27 - Por que morrem as flores",
        subtitle: "As mortes prematuras sob a ótica espírita",
        author: "João Ferreira",
        pdfUrl: "https://drive.google.com/file/d/14Q1u5ifxIs6BzvCdPyde7YJ_FaMpcSQ1/view?usp=sharing",
        frontCoverUrl: "assets/cordeis/27 - Por que morrem as flores/01.png",
        backCoverUrl: "assets/cordeis/27 - Por que morrem as flores/02.png",
    },
    {
        number: 28,
        type: "cordel",
        category: "Vida após a Morte",
        title: "Culpa e remorso",
        author: "João Ferreira",
        pdfUrl: "https://drive.google.com/file/d/1G2II7zTadpcH5InDjEfa40au5A_Ws_lL/view?usp=sharing",
        frontCoverUrl: "assets/cordeis/28 - Culpa e remorso/01.png",
        backCoverUrl: "assets/cordeis/28 - Culpa e remorso/02.png",
    },
    {
        number: 29,
        type: "cordel",
        category: "Vida após a Morte",
        title: "Eu sou",
        subtitle: "A busca pelo Cristo consolador",
        author: "João Ferreira",
        pdfUrl: "https://drive.google.com/file/d/1ho7Nb1WA6RGrPSrchgxnROcfPd55jY3a/view?usp=sharing",
        frontCoverUrl: "assets/cordeis/29 - Eu sou/01.png",
        backCoverUrl: "assets/cordeis/29 - Eu sou/02.png",
    },
    {
        number: 30,
        type: "cordel",
        category: "Vida após a Morte",
        title: "Um olhar para os pobres e estropiados",
        author: "João Ferreira",
        pdfUrl: "https://drive.google.com/file/d/12WEkb3lbcJSvtfD6thvA6bJDvuzgKtf4/view?usp=sharing",
        frontCoverUrl: "assets/cordeis/30 - Um olhar para os pobres e estropiados/01.png",
        backCoverUrl: "assets/cordeis/30 - Um olhar para os pobres e estropiados/02.png",
    },
    {
        number: 34,
        type: "cordel",
        category: "Vida após a Morte",
        title: "Gratidão sob a ótica espírita",
        author: "João Ferreira",
        pdfUrl: "https://drive.google.com/file/d/1cQwSpBTe1MEg8tRqONSBQ6taP0UqcqXj/view?usp=sharing",
        frontCoverUrl: "assets/cordeis/34 - Gratidão sob a ótica espírita/01.png",
        backCoverUrl: "assets/cordeis/34 - Gratidão sob a ótica espírita/02.png",
    },
    {
        number: 35,
        type: "cordel",
        category: "Vida após a Morte",
        title: "Animais, nós também.",
        subtitle: "A evolução dos animais sob a ótica espírita",
        author: "João Ferreira",
        pdfUrl: "https://drive.google.com/file/d/1e9u0cRjxX771oDoL1gAA7siRid9A2P69/view?usp=sharing",
        frontCoverUrl: "assets/cordeis/35 - Animais, nós também/01.png",
        backCoverUrl: "assets/cordeis/35 - Animais, nós também/02.png",
    },
    {
        number: 37,
        type: "cordel",
        category: "Vida após a Morte",
        title: "A depressão sob a ótica espírita",
        author: "João Ferreira",
        pdfUrl: "https://drive.google.com/file/d/1C2LFKvhWWrFZan3whIsEuCr1wG11-VPR/view?usp=sharing",
        frontCoverUrl: "assets/cordeis/37 -  A depressão sob a ótica espírita/01.png",
        backCoverUrl: "assets/cordeis/37 -  A depressão sob a ótica espírita/02.png",
    },
    {
        number: 38,
        type: "cordel",
        category: "Vida após a Morte",
        title: "Superiores e subordinados",
        subtitle: "A autoridade sob a ótica espírita",
        author: "João Ferreira",
        pdfUrl: "https://drive.google.com/file/d/1GTXuS1wysI_ILrLHh7LVij2VsVNYsFaD/view?usp=sharing",
        frontCoverUrl: "assets/cordeis/38 - Superiores e subordinados/01.png",
        backCoverUrl: "assets/cordeis/38 - Superiores e subordinados/02.png",
    },
    {
        number: 39,
        type: "cordel",
        category: "Vida após a Morte",
        title: "Vampirismo espiritual e emocional",
        author: "João Ferreira",
        pdfUrl: "https://drive.google.com/file/d/13kcmpsm9aUg3APWDp9U6Sfe4cvWPJd3k/view?usp=sharing",
        frontCoverUrl: "assets/cordeis/39 - Vampirismo espiritual e emocional/01.png",
        backCoverUrl: "assets/cordeis/39 - Vampirismo espiritual e emocional/02.png",
    },
    {
        number: 40,
        type: "cordel",
        category: "Mediunidade",
        title: "Deus",
        subtitle: "A evolução do pensamento humano sobre a existência do criador",
        author: "João Ferreira",
        pdfUrl: "https://drive.google.com/file/d/1IW36cJrlDDKVLw2pe25MgfZhSKgSXIMc/view?usp=sharing",
        frontCoverUrl: "assets/cordeis/40 - Deus/01.png",
        backCoverUrl: "assets/cordeis/40 - Deus/02.png",
    },
    {
        number: 41,
        type: "cordel",
        category: "Ética Espírita",
        title: "O recurso terapêutico do passe 1",
        author: "João Ferreira",
        pdfUrl: "https://drive.google.com/file/d/1A-wko7IAPss8cMZn7EeFTAiE0DXOMqzM/view?usp=sharing",
        frontCoverUrl: "assets/cordeis/41 - O recurso terapêutico do passe 1/01.png",
        backCoverUrl: "assets/cordeis/41 - O recurso terapêutico do passe 1/02.png",
    },
    {
        number: 42,
        type: "cordel",
        category: "Ética Espírita",
        title: "O recurso terapêutico do passe 2",
        subtitle: "O autopasse",
        author: "João Ferreira",
        pdfUrl: "https://drive.google.com/file/d/1ebLr04b8KXF_RnnLRoEooKLyWlIBfKTi/view?usp=sharing",
        frontCoverUrl: "assets/cordeis/42 - O recurso terapêutico do passe 2/01.png",
        backCoverUrl: "assets/cordeis/42 - O recurso terapêutico do passe 2/02.png",
    },
    {
        number: 43,
        type: "cordel",
        category: "Ética Espírita",
        title: "O recurso terapêutico do passe 3",
        subtitle: "Magnetismo na água",
        author: "João Ferreira",
        pdfUrl: "https://drive.google.com/file/d/1ONAWLQHZozWNjO1lvnZe4aPYOS4PIiXd/view?usp=sharing",
        frontCoverUrl: "assets/cordeis/43 - O recurso terapêutico do passe 3/01.png",
        backCoverUrl: "assets/cordeis/43 - O recurso terapêutico do passe 3/02.png",
    },
    {
        number: 44,
        type: "cordel",
        category: "Ética Espírita",
        title: "Lições da parábola",
        author: "João Ferreira",
        pdfUrl: "https://drive.google.com/file/d/1vTdM1C_UCX64-eUEZ4itRwEynghqgum4/view?usp=sharing",
        frontCoverUrl: "assets/cordeis/44 - Lições da parábola/01.png",
        backCoverUrl: "assets/cordeis/44 - Lições da parábola/02.png",
    },
    {
        number: 45,
        type: "cordel",
        category: "Ética Espírita",
        title: "Embainha tua espada",
        subtitle: "A conduta cristã diante das agressões",
        author: "João Ferreira",
        pdfUrl: "https://drive.google.com/file/d/1TrXAwz7ExSx0XFgsZcE-v-mBPUduSnOR/view?usp=sharing",
        frontCoverUrl: "assets/cordeis/45 - Embainha tua espada/01.png",
        backCoverUrl: "assets/cordeis/45 - Embainha tua espada/02.png",
    },
    {
        number: 46,
        type: "cordel",
        category: "Ética Espírita",
        title: "A compaixão sob a ótica espírita",
        author: "João Ferreira",
        pdfUrl: "https://drive.google.com/file/d/12P3HXvlDYxoJ5VIHZY7h-Bz4qn5Qm9yS/view?usp=sharing",
        frontCoverUrl: "assets/cordeis/46 - A compaixão sob a ótica espírita/01.png",
        backCoverUrl: "assets/cordeis/46 - A compaixão sob a ótica espírita/02.png",
    },
    {
        number: 47,
        type: "cordel",
        category: "Ética Espírita",
        title: "Espíritos protetores, familiares e simpáticos",
        subtitle: "A missão dos anjos guardiões",
        author: "João Ferreira",
        pdfUrl: "https://drive.google.com/file/d/1fHKDx35wVANMjmx3Q7Okx-ZJagiWEiZc/view?usp=sharing",
        frontCoverUrl: "assets/cordeis/47 - Espíritos protetores, familiares e simpáticos/01.png",
        backCoverUrl: "assets/cordeis/47 - Espíritos protetores, familiares e simpáticos/02.png",
    },
    {
        number: 48,
        type: "cordel",
        category: "Ética Espírita",
        title: "Tatuagem sob a otica espirita",
        author: "João Ferreira",
        pdfUrl: "https://drive.google.com/file/d/12fxJlU2a6QhW5iSRAD2n2WOl01loXbn3/view?usp=sharing",
        frontCoverUrl: "assets/cordeis/48 - Tatuagem sob a otica espirita/01.png",
        backCoverUrl: "assets/cordeis/48 - Tatuagem sob a otica espirita/02.png",
    },
    {
        number: 49,
        type: "cordel",
        category: "Ética Espírita",
        title: "Transição planetária",
        subtitle: "A transformação da terra em mundo de regeneração",
        author: "João Ferreira",
        pdfUrl: "https://drive.google.com/file/d/1_oqfLx9GDQQ4ILN0RQvYjev6u_o5caF2/view?usp=sharing",
        frontCoverUrl: "assets/cordeis/49 - Transição planetária/01.png",
        backCoverUrl: "assets/cordeis/49 - Transição planetária/02.png",
    },
    {
        number: 50,
        type: "cordel",
        category: "Ética Espírita",
        title: "Paraíso, inferno e purgatório",
        author: "João Ferreira",
        pdfUrl: "https://drive.google.com/file/d/1ONdrv8PpBov7K_2-1pV32jUBIJbgw_ER/view?usp=sharing",
        frontCoverUrl: "assets/cordeis/50 - Paraíso, inferno e purgatório/01.png",
        backCoverUrl: "assets/cordeis/50 - Paraíso, inferno e purgatório/02.png",
    },
    {
        number: 51,
        type: "cordel",
        category: "Ética Espírita",
        title: "Pilares da doutrina espírita",
        author: "João Ferreira",
        pdfUrl: "https://drive.google.com/file/d/1FmsvuOvcauYtrRGSjix9ZT2roNjrMqsm/view?usp=sharing",
        frontCoverUrl: "assets/cordeis/51 - Pilares da doutrina espírita/01.png",
        backCoverUrl: "assets/cordeis/51 - Pilares da doutrina espírita/02.png",
    },
]